### ISSUE TITLE
Titles in financial overview can be on top of each other

### ISSUE THREAD

**Issue by kasbah** [opencollective/opencollective-frontend#1020]
![image](https://user-images.githubusercontent.com/206854/48222936-c3d1ca80-e38d-11e8-9184-8722662e9fae.png)

https://opencollective.com/manyverse

**Comment by piamancini** [comment]
cc / @znarf

**Comment by znarf** [comment]
Closing as it's duplicate with https://github.com/opencollective/opencollective/issues/1434
