### ISSUE TITLE
Github link needs an icon?

### ISSUE THREAD

**Issue by kasbah** [opencollective/opencollective-frontend#1021]
I feel like the `owner/repo` format doesn't tell a user what it's going to link to. E.g. for gitextensions it just says `gitextensions/gitextensions`.  Maybe there used to be an icon there? 

![image](https://user-images.githubusercontent.com/206854/48223855-1318fa80-e390-11e8-9d3b-c5f2a8a740dc.png)

https://opencollective.com/gitextensions

**Comment by kasbah** [comment]
Looks like all that's missing is the style to add the icon.

```js
document.querySelector(".githubHandle").style = "background: url(/static/icons/github-handler.svg) no-repeat 0px 6px; padding-left: 22px;"
```

**Comment by Betree** [comment]
This should be fixed by https://github.com/opencollective/opencollective-frontend/pull/936 I'm going to rebase it and merge it now.

**Comment by Betree** [comment]
@kasbah The fix is deployed and you should now see this beautiful Github icon on your collective page:

![Preview](https://user-images.githubusercontent.com/1556356/48260614-5d47bd80-e41c-11e8-9dde-40a975e77096.png)

Thanks for reporting the issue!
