### ISSUE TITLE
Search, Sort, Filter, Pagination features

### ISSUE THREAD

**Issue by coooolers** [opencollective/opencollective-frontend#103]
Can we expect that you add these essential features?

Thanks

**Comment by asood123** [comment]
What context do you want this functionality? Like searching the site or a specific collective's transactions, etc.

**Comment by coooolers** [comment]
Lik searching/paginating the open source projects, people who contributed money for a particular project, similarly the backers and sponsors. If possible, use Elastic Search to search project descriptions, etc.

In the Admin panel, same features should be there.

Any plans?

**Comment by asood123** [comment]
All of those are on the list - hope to launch some of those early next quarter. We are a small team of 2 engineers (looking for our 3rd), so we have a long backlog of features to deliver.

**Comment by coooolers** [comment]
Ok fine Thanks for the update

**Comment by pixelastic** [comment]
Hello all,

Tim from Algolia here. Maybe we could help? In addition to what we pledge to each individual projects as a company, we would also like to offer our help in improving the [/search](https://opencollective.com/search) page of the current website.

The main features we would add to the current search would be results displayed in real time (as opposed to having to submit the form), typo-tolerance, speed and custom popularity ranking. Pagination and filtering on backers/companies/etc is also completely possible, depending on the data you have available.

At the very minium we can give you access to our [Algolia For Open-Source free plan](https://www.algolia.com/for-open-source), but I'd be happy to go even further and help you build the actual search page.

Let me know if that's something you would be interested in.

Cheers,

Tim

**Comment by piamancini** [comment]
Hi @pixelastic ! 
Thank you for reaching out. I've assigned this to @HipsterBrown that built search so he can jump on the thread. 
With regards to the plan, we already have access to it (many many thanks!!)!

**Comment by znarf** [comment]
Search is implemented. The rest is stale, closing. 

(Currently cleaning all issues in that repository).
