### ISSUE TITLE
Labeling existing issues and new issues 

### ISSUE THREAD

**Issue by flickz** [opencollective/opencollective-frontend#1326]
Labeling issues based on their current status, priority  and difficulty would assist new contributors like me, it is usually helpful to have issues with "good first contribution" to help get around the code base.

**Comment by znarf** [comment]
We decided to centralize all our issues in this repository.
https://github.com/opencollective/opencollective

Most of them are already labelled, but we're gonna do a pass in the next days to add more like "good first contribution".

Out of clarity, we're gonna also move all remaining issues to the main one. That was not easy before but now we can move issues between repositories on GitHub!
