### ISSUE TITLE
Replace `styled-jsx` usage with `styled-components`

### ISSUE THREAD

**Issue by HipsterBrown** [opencollective/opencollective-frontend#442]
In conjunction with https://github.com/opencollective/frontend/pull/434, we will be removing `styled-jsx` (and the postcss integration) with `styled-components`. See the RFC for more details about the change.

TODO:

- [x] replace the global styles in `src/pages/_document.js` and `src/components/Header.js` with a single [`injectGlobal`](https://www.styled-components.com/docs/api#injectglobal) declaration in `src/pages/_document.js`
- [x] create a [Theme](https://www.styled-components.com/docs/advanced#theming) with common colors and sizing values (?)
- [x] create [media templates](https://www.styled-components.com/docs/advanced#media-templates) for consistent responsive settings
- [ ] update all pages (`src/pages/`) to use `styled-components`
- [ ] update all components (`src/components/`) to use `styled-components`

**Comment by znarf** [comment]
There is no real path to migrate. We will do that progressively.
