### ISSUE TITLE
Update spanish string translations

### ISSUE THREAD

**Issue by patcon** [opencollective/opencollective-frontend#489]
@eatskolnikov brough up in Slack that the spanish translations are out of date. (Thanks! :tada:)

The file handling this localization is here: https://github.com/opencollective/frontend/blob/master/src/lang/es.json

Localization docs are here, and could perhaps do with an update if they don't cover a case like this? Dunno! whatever seems right :)
https://developer.opencollective.com/#/frontend/localize
https://github.com/opencollective/opencollective/blob/master/docs/frontend/localize.md

You want to run with this, @eatskolnikov?

**Comment by piamancini** [comment]
hey! I have an opened PR for this. Happy to merge as is and receive help for the rest!

**Comment by eatskolnikov** [comment]
@piamancini what's the PR number? I can send commits to your PR.

**Comment by eatskolnikov** [comment]
@patcon and @piamancini The PR is ready for review :p

**Comment by znarf** [comment]
Stale. Closing.
