### ISSUE TITLE
RSS/Atom feed for Updates

### ISSUE THREAD

**Issue by clehner** [opencollective/opencollective-frontend#5239]
Requested by a @ssbc backer

**Comment by sbinlondon** [comment]
Hi @bkardell please open issues with more details on our main repository here: https://github.com/opencollective/opencollective

**Comment by sbinlondon** [comment]
Hi @clehner please open issues on our main repository here: https://github.com/opencollective/opencollective

**Comment by clehner** [comment]
Thank you for the pointer @sbinlondon . I found an existing issue for it: https://github.com/opencollective/opencollective/issues/3504
