### ISSUE TITLE
Remove any base64 PNGs from SVG assets

### ISSUE THREAD

**Issue by XhmikosR** [opencollective/opencollective-frontend#525]
The SVGs should be pure vectors.

**Comment by znarf** [comment]
@XhmikosR This sounds similar to https://github.com/opencollective/frontend/issues/524

I guess you're talking about https://github.com/opencollective/frontend/tree/master/src/public/svg

In which files do you see any base64 encoding?

**Comment by XhmikosR** [comment]
Not related. This is for the SVGs that include a base64 PNG. The other issue is for base64 encoding the whole SVGs.

An example is https://github.com/opencollective/frontend/blob/35f52ebde057bd80e4a65331c4748e14da57d6e4/src/static/images/organization.svg

More results in https://github.com/opencollective/frontend/search?q=base64&unscoped_q=base64

**Comment by znarf** [comment]
I agree, the example you provided `organization.svg` should be a pure svg and not contain any base64.

**Comment by XhmikosR** [comment]
There are many more, just look at the codebase :)

**Comment by znarf** [comment]
For the SVGs in the static folder, if you have a solution, feel free to submit a PR and provide the command to do it. I don't think that needs to be in the build process now, fixing the files in the repository should be enough.

**Comment by XhmikosR** [comment]
No, this needs to be done manually because the PNGs that are in the SVGs serve a purpose visually :P
