### ISSUE TITLE
Monthly spending for active collectives is off on Homepage

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective-frontend#630]
![screen shot 2018-07-27 at 16 11 27](https://user-images.githubusercontent.com/806/43325837-c9f6640c-91b7-11e8-94de-ddc3337a863f.png)

I don't think `333k` for webpack and `111k` for material-ui are real monthly values.

**Comment by piamancini** [comment]
It's probably not taking into account we use numbers with 00 in the db

**Comment by znarf** [comment]
Looks fixed.
