### ISSUE TITLE
Unwanted HTML attributes when using styled components

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective-frontend#631]
Eg:

```<div class="sc-dnqmqq ddDArR" height="52,,65" width="52,,65"></div></a></div></div><p class="Text__P-s18kcxxs-1 goephr" font-size="1.4rem" font-weight="bold">```

The solution seems to be using `clean-tag`: https://www.npmjs.com/package/clean-tag

**Comment by znarf** [comment]
@HipsterBrown was that fixed in https://github.com/opencollective/frontend/pull/661 ?

**Comment by HipsterBrown** [comment]
I still need to update the Text components to use `clean-tag`. Good reminder. :+1:

**Comment by znarf** [comment]
Is that done now @HipsterBrown ?

**Comment by HipsterBrown** [comment]
Yes, thanks for the reminder.
