### ISSUE TITLE
Cache should be localization aware

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective-frontend#671]
- visitor A (with french default language) visits a collective page with, the page will be stored at cloudflare edge in french
- a few seconds after, visitor B (with english default language) visits the collective page in the same region, the page will be displayed in french

Visitors with english as default language should never see a page displayed in french.

**Comment by znarf** [comment]
Reported on Twitter too: https://twitter.com/dog_awoo/status/1034445551914377217

Short term fix: disable frontend cache or translation.

**Comment by xdamman** [comment]
Looks like we could play with custom caching keys https://support.cloudflare.com/hc/en-us/articles/115004290387-Using-Custom-Cache-Keys
or with cloud flare workers to manage that better https://developers.cloudflare.com/workers/reference/cloudflare-features/#custom-cache-keys

**Comment by xdamman** [comment]
Copy pasting @znarf's comments from Slack:

>I don’t think that’s right, users should be able to use the language they want, whatever the browser settings
>browser settings can be used to detect a default, think about going in a cybercafé in China, you want to opt out
>we can’t generate a custom header like X-Lang for the main server request, this is where cookies are interesting
>there is also the possibility of client only localization, but this is a bit broken for React (server html !== client html)

Agreed. So looks like we can't avoid the use of cookies.

But in the meantime, isn't it a good mitigation to use the request header?
It's anyway how it works today.

**Comment by znarf** [comment]
We implemented long time ago a quick fix to disable caching of localized pages:
https://github.com/opencollective/opencollective-frontend/pull/817
