### ISSUE TITLE
createCollective page should not fetch data if slug is undefined

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective-frontend#816]
Context: In the createCollective page, when slug is undefined.

Actual: A GraphQL is triggered with an undefined slug as parameter (through addCollectiveCoverData/getCollectiveCoverQuery)

Expected: If slug is undefined,  no GraphQL query should be triggered

**Comment by Betree** [comment]
Is there a use case where having an `undefined` slug would be needed? 

If not, we could also put a new constraint in DB and never allow creating a collective without a slug.
