### ISSUE TITLE
Link to events should not reload the app

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective-frontend#891]
![screen shot 2018-10-05 at 18 16 37](https://user-images.githubusercontent.com/806/46546991-e5412180-c8ca-11e8-9b54-455332f39f43.png)

**Comment by znarf** [comment]
@xdamman https://github.com/opencollective/opencollective-frontend/commit/5b2e73de27fe2c5aba255302641f22efa39be631#diff-c28c1239c5958549ffae51754533047eR35

Shouldn't that be the opposite? "continue with default behavior of <a href>" when `this.isIframe` return true?

And by the way, what is this `this.isIframe`? Should that still be supported?

**Comment by xdamman** [comment]
it's for embedding the list of events on another website.
In that case, the link to the event needs to open in the _parent window.

try locally with http://localhost:3000/static/widgets.test.html
